# --------------------------------------------------------------------------------------------------
# General Configuration
# --------------------------------------------------------------------------------------------------

# Server parameters
server:
  port: 60695
  error.include-stacktrace: always

# Maximum upload and request sizes
multipart:
  maxFileSize: '10Mb'
  maxRequestSize: '10Mb'

# Spring parameters
spring:
  profiles.active: 'dev'
  http.converters.preferred-json-mapper: gson

# Proxy parameters (With you want there is problem to connect to REST PKI, cased by a proxy)
proxy:
  host: null
  port: null
  # Authentication
  username: null
  password: null

# --------------------------------------------------------------------------------------------------
# Lacuna Configuration
# --------------------------------------------------------------------------------------------------

# Trust in Lacuna Test PKI (for development purposes only!)
trustLacunaTestRoot: false
# THIS SHOULD NEVER BE USED ON A PRODUCTION ENVIRONMENT!

# REST PKI parameters
rest-pki:
  # ======================================================
  #       >>>> PASTE YOUR REST PKI ACCESS TOKEN BELOW <<<<
  # ======================================================
  accessToken: 'QPK_s7eVFFitenHh-6c5PBEk1nlssA5OQkbpyZWBnGEvG7cK3lTs4Toxs2STulwrRPORtJbT8m9V_hR_FTZTPUnzqgcWC4xmd7QYPJZIXBIw2HgsjTc6GAEL6N1TXSBLBNDz_FkwwnlKCk53YPBa4AAnWZBMfe5riah1F_BpinrxKGX1ewohIgxTHxzAeRtQcwRB8XW6yk9TR6GL7mK5ky0o2u00VnSgzrOLd8F0cuV44257dZlumMNTBkq2fBeAUWTGNo3Ydwgn5k5BYM2hfCdWDssiRv-GLyqxjo7t4brq2hUK6QBXisMXfZ4dSd_rRQvpVpa1cdS4KansOxanQX9M2fNU8Gmf6I22SwZ0c5wM9qlkv5Q-LZOYtakrkdqxY-lCUDog9goPCBQenSt128thFko3uFKdAyiZCiL5fTi9I-ZBGNbNB7rf6nACvlWAH_jkGpfSFnrarSbtzniVXI7wSf8ge4iCeP92HT9CNSbRkGnBYRl-ryr39nqz7--vYpJ6kw'
  # This is a TRIAL token. It will be expired at 01/04/2019
  # If the REST PKI sample doesn't work, please contact our support by
  # email: suporte@lacunasoftware.com

  # In order to use this sample on a "on premises" installation of REST PKI, fill the field below
  # with the URL address of your REST PKI installation (with the trailing '/' character)
  endpoint: null

# PKI Express parameters
pki-express:
  # List of custom trusted roots. In this sample, we will get the certificate files on
  # resources/static folder
  trustedRoots: null

  # Offline mode. Set this, if you want to PKI Express to run on offline mode. This mode is useful
  # when there is no network available
  offline: false

# Web PKI parameters
web-pki:
  # Base64-encoded binary license for the Web PKI. This value is passed to Web PKI component's
  # constructor on JavaScript
  license: null
